name: CI/CD Pipeline

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  test-and-build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install dependencies (with legacy peer deps)
        run: npm ci --legacy-peer-deps

      - name: Run tests
        run: npm test
        env:
          NODE_ENV: test

      - name: Build application
        run: npm run build

      - name: Build Docker image
        run: docker build -t qliq-server .

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: marwan7771
          password: dckr_pat_XlczZSUMk77JrSuKjI01AbEMBTI

      - name: Push to Docker Hub
        run: |
          docker tag qliq-server marwan7771/qliq-server:latest
          docker push marwan7771/qliq-server:latest
